# Generated by Django 6.0.6 on 2026-07-08 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userinactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='website_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
