# Generated by Django 6.0.7 on 2026-07-21 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='last_triggered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('BREAK', 'Break Reminder'), ('OVERWORK', 'Overwork Alert'), ('PRODUCTIVITY', 'Productivity Alert'), ('IDLE', 'Idle Too Long'), ('NON_PRODUCTIVE', 'Non Productive Limit'), ('PRODUCTIVE_SESSION', 'Productive Work Session')], max_length=30),
        ),
    ]
