# Generated by Django 6.0.7 on 2026-07-23 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_last_triggered_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('IDLE', 'Idle Too Long'), ('NON_PRODUCTIVE', 'Non Productive Limit'), ('PRODUCTIVE_SESSION', 'Productive Work Session')], max_length=30),
        ),
    ]
