"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from datetime import timedelta
from pathlib import Path

from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ------------------------------------------------------------------------------
# SECURITY
# ------------------------------------------------------------------------------

SECRET_KEY = config("SECRET_KEY")

_debug_val = config("DEBUG", default="True")
DEBUG = str(_debug_val).lower() in ("true", "1", "t", "yes", "y")

# Allow multiple comma-separated hosts in production.
_allowed_hosts = config("ALLOWED_HOSTS", default="127.0.0.1,localhost")
ALLOWED_HOSTS = [host.strip() for host in _allowed_hosts.split(",")]

if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# ------------------------------------------------------------------------------
# APPLICATIONS
# ------------------------------------------------------------------------------

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "rest_framework",
    "rest_framework_simplejwt.token_blacklist",

    "users",
    "reports",
    "notifications",
    "recommendations",
    "corsheaders",
     "website_categories",
    "settings",
    "chatbot",
    "focus",
    "admin_notifications",

]

# ------------------------------------------------------------------------------
# MIDDLEWARE
# ------------------------------------------------------------------------------

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

# ------------------------------------------------------------------------------
# TEMPLATES
# ------------------------------------------------------------------------------

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

# ------------------------------------------------------------------------------
# DATABASE
# ------------------------------------------------------------------------------

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": config("DB_NAME"),
        "USER": config("DB_USER"),
        "PASSWORD": config("DB_PASSWORD"),
        "HOST": config("DB_HOST"),
        "PORT": config("DB_PORT"),
    }
}

# ------------------------------------------------------------------------------
# AUTHENTICATION
# ------------------------------------------------------------------------------

AUTH_USER_MODEL = "users.User"

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# ------------------------------------------------------------------------------
# INTERNATIONALIZATION
# ------------------------------------------------------------------------------

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Kolkata"

USE_I18N = True

USE_TZ = True

# ------------------------------------------------------------------------------
# STATIC FILES
# ------------------------------------------------------------------------------

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ------------------------------------------------------------------------------
# DJANGO REST FRAMEWORK
# ------------------------------------------------------------------------------

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
    'users.authentication.FocusGuardJWTAuthentication',
),
}

# ------------------------------------------------------------------------------
# SIMPLE JWT
# ------------------------------------------------------------------------------

from datetime import timedelta

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=24),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),

    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": False,

    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,

    "AUTH_HEADER_TYPES": ("Bearer",),
}

# ------------------------------------------------------------------------------
# EMAIL CONFIGURATION
# ------------------------------------------------------------------------------

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

EMAIL_HOST = config("EMAIL_HOST")
EMAIL_PORT = config("EMAIL_PORT", cast=int)

EMAIL_HOST_USER = config("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD")

EMAIL_USE_TLS = config("EMAIL_USE_TLS", cast=bool)
EMAIL_TIMEOUT = config("EMAIL_TIMEOUT", default=10, cast=int)

DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL")

# ------------------------------------------------------------------------------
# LLM CONFIGURATION
# ------------------------------------------------------------------------------

GROK_API_KEY = config("GROK_API_KEY", default="")
GEMINI_API_KEY = config("GEMINI_API_KEY", default="")
OPENAI_API_KEY = config("OPENAI_API_KEY", default="")

PRIMARY_LLM = config("PRIMARY_LLM", default="gemini")

GEMINI_MODEL = config("GEMINI_MODEL", default="gemini-3.5-flash")
GROQ_API_KEY = config("GROQ_API_KEY")
GROQ_MODEL = config("GROQ_MODEL")

# Existing APIs
GEMINI_RECOMMENDATION_API_KEY = config("GEMINI_RECOMMENDATION_API_KEY")
GEMINI_CATEGORY_API_KEY = config("GEMINI_CATEGORY_API_KEY")

# AI Coach
CHATBOT_GEMINI_API_KEY = config("CHATBOT_GEMINI_API_KEY")
CHATBOT_GROQ_API_KEY = config("CHATBOT_GROQ_API_KEY")

# Organization Admin AI Assistant
GEMINI_ORGANIZATION_ADMIN_API_KEY = config(
    "GEMINI_ORGANIZATION_ADMIN_API_KEY",
    default=CHATBOT_GEMINI_API_KEY or GEMINI_API_KEY,
)
GEMINI_ORGANIZATION_ADMIN_MODEL = config(
    "GEMINI_ORGANIZATION_ADMIN_MODEL",
    default="gemini-3.5-flash",
)
GROK_ORGANIZATION_ADMIN_API_KEY = config(
    "GROK_ORGANIZATION_ADMIN_API_KEY",
    default=config(
        "GROQ_ORGANIZATION_ADMIN_API_KEY",
        default=CHATBOT_GROQ_API_KEY or GROQ_API_KEY,
    ),
)

# Focus Planner
FOCUS_PLAN_GEMINI_API_KEY = config("FOCUS_PLAN_GEMINI_API_KEY")
FOCUS_PLAN_GROQ_API_KEY = config("FOCUS_PLAN_GROQ_API_KEY")
# ------------------------------------------------------------------------------
# NOTIFICATION SETTINGS
# ------------------------------------------------------------------------------

BREAK_REMINDER_HOURS = 3

FRONTEND_URL = config("FRONTEND_URL", default="http://localhost:3000").rstrip("/")

_cors_origins = config("CORS_ALLOWED_ORIGINS", default="")
CORS_ALLOWED_ORIGINS = [
    FRONTEND_URL,
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:3001",
    "http://127.0.0.1:3001",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:5174",
    "http://127.0.0.1:5174",
    "http://localhost:5175",
]

# Allow additional origins from environment separated by commas
if _cors_origins:
    CORS_ALLOWED_ORIGINS.extend([origin.strip() for origin in _cors_origins.split(",")])


CORS_ALLOW_CREDENTIALS = True

