# Generated by Django 6.0.7 on 2026-07-25 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FocusGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_metric', models.CharField(choices=[('Deep Work Session', 'Deep Work Session'), ('Social Media Limit', 'Social Media Limit'), ('Daily Focus Score Target', 'Daily Focus Score Target'), ('Daily Screen Time Limit', 'Daily Screen Time Limit'), ('Context Switch Limit', 'Context Switch Limit'), ('Break Frequency Target', 'Break Frequency Target'), ('No-Distraction Block', 'No-Distraction Block')], max_length=100)),
                ('target_value', models.FloatField()),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=10)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('On Track', 'On Track'), ('At Risk', 'At Risk'), ('Completed', 'Completed')], default='On Track', max_length=20)),
                ('progress', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='focus_goals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
