# Generated by Django 6.0.7 on 2026-07-25 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FocusPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='focus.focusgoal')),
            ],
        ),
    ]
