# Generated by Django 6.0.6 on 2026-07-05 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_invitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('SUB_ADMIN', 'Organization Admin'), ('USER', 'Employee')], default='USER', max_length=20),
        ),
    ]
