# Generated by Django 6.0.6 on 2026-07-06 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_invitation_role_activitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInactivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inactive_from', models.DateTimeField()),
                ('active_again_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inactivity_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
