# Generated by Django 6.0.6 on 2026-07-09 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_employeedeactivationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinactivity',
            name='tab_title',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='userinactivity',
            name='website_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userinactivity',
            name='website_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
