# Generated by Django 6.0.7 on 2026-07-21 12:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_useranalytics'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='productivity_type',
            field=models.CharField(choices=[('PRODUCTIVE', 'Productive'), ('NON_PRODUCTIVE', 'Non Productive'), ('NEUTRAL', 'Neutral')], default='NEUTRAL', max_length=20),
        ),
        migrations.AddField(
            model_name='useranalytics',
            name='neutral_time',
            field=models.DurationField(default=datetime.timedelta),
        ),
    ]
