# Generated by Django 6.0.7 on 2026-07-23 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_activitylog_productivity_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAnalytics',
        ),
    ]
