# Generated by Django 6.0.7 on 2026-07-25 10:28

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_delete_useranalytics'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productive_time', models.DurationField(default=datetime.timedelta)),
                ('non_productive_time', models.DurationField(default=datetime.timedelta)),
                ('neutral_time', models.DurationField(default=datetime.timedelta)),
                ('idle_time', models.DurationField(default=datetime.timedelta)),
                ('websites_visited', models.PositiveIntegerField(default=0)),
                ('tab_switches', models.PositiveIntegerField(default=0)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
