# Generated by Django 6.0.7 on 2026-07-26 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_useranalytics'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='invite_code',
            field=models.CharField(default='FGA-TEMP', max_length=15),
            preserve_default=False,
        ),
    ]
