# Generated by Django 6.0.7 on 2026-07-26 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_invitation_invite_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='invite_code',
            field=models.CharField(editable=False, max_length=15, unique=True),
        ),
    ]
