# Generated by Django 6.0.7 on 2026-07-26 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_invitation_invite_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='max_employees',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
